version: '3.8'

services:
  socks-dev:
    container_name: socks-dev
    privileged: true
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../build:/socks:cached 
    restart: unless-stopped
    entrypoint: tail -f /dev/null  
  socks-test:
    container_name: socks-test
    image: alpine:3.18
    network_mode: "container:socks-dev"
    depends_on:
      - socks-dev
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached 
    entrypoint: tail -f /dev/null  